# Generated by Django 6.0 on 2025-12-08 05:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='Registration Number')),
                ('gst_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid GST number', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')], verbose_name='GST Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('mobile', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number', regex='^[6-9]\\d{9}$')], verbose_name='Mobile Number')),
                ('alternate_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('address_line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('pincode', models.CharField(max_length=6, verbose_name='Pincode')),
                ('country', models.CharField(default='India', max_length=100, verbose_name='Country')),
                ('business_type', models.CharField(choices=[('essential', 'Essential'), ('non_essential', 'Non-Essential'), ('services', 'Services'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('wholesale', 'Wholesale'), ('other', 'Other')], max_length=50, verbose_name='Business Type')),
                ('business_subtype', models.CharField(max_length=100, verbose_name='Business Subtype')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Industry')),
                ('company_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Company Size')),
                ('established_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Established Year')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Company Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50, verbose_name='Timezone')),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=20, verbose_name='Date Format')),
                ('password_expiry_days', models.PositiveIntegerField(default=90, verbose_name='Password Expiry (Days)')),
                ('max_login_attempts', models.PositiveIntegerField(default=5, verbose_name='Max Login Attempts')),
                ('session_timeout', models.PositiveIntegerField(default=30, verbose_name='Session Timeout (Minutes)')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email Notifications')),
                ('sms_notifications', models.BooleanField(default=True, verbose_name='SMS Notifications')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push Notifications')),
                ('auto_generate_password', models.BooleanField(default=True, verbose_name='Auto Generate Passwords')),
                ('require_employee_activation', models.BooleanField(default=True, verbose_name='Require Employee Activation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
                'db_table': 'company_settings',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=50, unique=True, verbose_name='Employee Code')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number', regex='^[6-9]\\d{9}$')], verbose_name='Mobile Number')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('staff', 'Staff'), ('viewer', 'Viewer'), ('accountant', 'Accountant'), ('hr', 'HR Manager')], default='staff', max_length=50, verbose_name='Role')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Department')),
                ('designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation')),
                ('joining_date', models.DateField(verbose_name='Joining Date')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salary')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('intern', 'Intern')], default='full_time', max_length=50, verbose_name='Employment Type')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('temp_password', models.BooleanField(default=True, verbose_name='Temporary Password')),
                ('last_password_change', models.DateTimeField(auto_now_add=True, verbose_name='Last Password Change')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('on_leave', 'On Leave')], default='active', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employee_profiles/', verbose_name='Profile Picture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Login Time')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('success', models.BooleanField(default=True, verbose_name='Login Successful')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to='companies.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Login History',
                'verbose_name_plural': 'Employee Login Histories',
                'db_table': 'employee_login_history',
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['email'], name='companies_email_6c1508_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['mobile'], name='companies_mobile_7c8fcc_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['gst_number'], name='companies_gst_num_b1f787_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_verified'], name='companies_is_veri_16da10_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['created_at'], name='companies_created_c84a3d_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_code'], name='employees_employe_6fc092_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='employees_email_f66e96_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'status'], name='employees_company_311632_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'role'], name='employees_company_1b196a_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['joining_date'], name='employees_joining_3e1e6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('company', 'email')},
        ),
        migrations.AddIndex(
            model_name='employeeloginhistory',
            index=models.Index(fields=['employee', 'login_time'], name='employee_lo_employe_597f77_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeloginhistory',
            index=models.Index(fields=['login_time'], name='employee_lo_login_t_067349_idx'),
        ),
    ]
