# Generated by Django 5.2.7 on 2025-12-17 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_createemployee_customer_customercontact_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_numbers',
            field=models.TextField(blank=True, help_text='Separate multiple numbers with ;', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_persons',
            field=models.TextField(blank=True, help_text='Separate multiple person with ;', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_numbers',
            field=models.TextField(blank=True, help_text='Separate multiple numbers with ;', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_persons',
            field=models.TextField(blank=True, help_text='Separate multiple person with ;', null=True),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_contact', to='companies.customer'),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_contact', to='companies.vendor'),
        ),
    ]
