# Generated by Django 5.2.7 on 2025-12-18 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_customer_contact_numbers_customer_contact_persons_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createemployee',
            options={'ordering': ['-created_at'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='createemployee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='createemployee',
            name='employee_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='createemployee',
            constraint=models.UniqueConstraint(fields=('company', 'employee_code'), name='unique_employee_code_per_company'),
        ),
    ]
