# Generated by Django 5.2.7 on 2025-12-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_createemployee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
