# Generated by Django 6.0 on 2025-12-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_customer_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='enable_3day_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='enable_7day_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='enable_expiry_day_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_national_permit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='national_permit_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='notification_emails',
            field=models.TextField(blank=True, help_text='Separate multiple emails with ;', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='notification_phone_numbers',
            field=models.TextField(blank=True, help_text='Separate multiple numbers with ;', null=True),
        ),
    ]
