# Generated by Django 6.0 on 2025-12-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_vehicle_enable_3day_reminder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='road_tax_expiry',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='road_tax',
            field=models.JSONField(blank=True, default=list, help_text="State-wise road tax expiry dates in format: [{'state': 'MH', 'expiry_date': '2024-12-31'}, ...]"),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
