# Generated by Django 6.0 on 2025-12-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_remove_vehicle_road_tax_expiry_vehicle_road_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='state_permits',
            field=models.JSONField(blank=True, default=list, help_text="State-wise permits in format: [{'state': 'MH', 'expiry_date': '2024-12-31'}, ...]"),
        ),
    ]
