# Generated by Django 6.0 on 2025-12-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_item_item_name_alter_vehicle_vehicle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
    ]
